/*
Autogenerated by C:\svn\sdr-rnav\sdr_rnav_dsp\c\inc\make_receiver_stat.pl
on Thu Oct 10 16:31:19 2013
from receiver_stat.h

*/
#ifndef __RSTAT_PL_ACCESS_H
#define __RSTAT_PL_ACCESS_H

#include "receiver_stat.h"
void dp_pl_rstat_set_strength_ratio(receiver_stat_t *r,float  v);
float  dp_pl_rstat_get_strength_ratio(receiver_stat_t *r);
void dp_pl_rstat_set_have_carrier(receiver_stat_t *r,dp_bool_t  v);
dp_bool_t  dp_pl_rstat_get_have_carrier(receiver_stat_t *r);
void dp_pl_rstat_set_run_fft(receiver_stat_t *r,dp_bool_t  v);
dp_bool_t  dp_pl_rstat_get_run_fft(receiver_stat_t *r);
void dp_pl_rstat_set_use_mixer(receiver_stat_t *r,dp_bool_t  v);
dp_bool_t  dp_pl_rstat_get_use_mixer(receiver_stat_t *r);
void dp_pl_rstat_set_strength_ratio_lpf(receiver_stat_t *r,float  v);
float  dp_pl_rstat_get_strength_ratio_lpf(receiver_stat_t *r);
void dp_pl_rstat_set_tune_freq(receiver_stat_t *r,uint32_t  v);
uint32_t  dp_pl_rstat_get_tune_freq(receiver_stat_t *r);
void dp_pl_rstat_set_mixer_lo_freq(receiver_stat_t *r,int32_t  v);
int32_t  dp_pl_rstat_get_mixer_lo_freq(receiver_stat_t *r);
void dp_pl_rstat_set_ref30_period(receiver_stat_t *r,float  v);
float  dp_pl_rstat_get_ref30_period(receiver_stat_t *r);
void dp_pl_rstat_set_nf_sr(receiver_stat_t *r,uint32_t  v);
uint32_t  dp_pl_rstat_get_nf_sr(receiver_stat_t *r);
void dp_pl_rstat_set_buffer_count(receiver_stat_t *r,uint32_t  v);
uint32_t  dp_pl_rstat_get_buffer_count(receiver_stat_t *r);
void dp_pl_rstat_set_var30_period(receiver_stat_t *r,float  v);
float  dp_pl_rstat_get_var30_period(receiver_stat_t *r);
void dp_pl_rstat_set_radio(receiver_stat_t *r,dp_base_t * v);
dp_base_t * dp_pl_rstat_get_radio(receiver_stat_t *r);
void dp_pl_rstat_set_phase_diff_lpf(receiver_stat_t *r,float  v);
float  dp_pl_rstat_get_phase_diff_lpf(receiver_stat_t *r);
void dp_pl_rstat_set_phase_diff(receiver_stat_t *r,float  v);
float  dp_pl_rstat_get_phase_diff(receiver_stat_t *r);
void dp_pl_rstat_set_mixer(receiver_stat_t *r,dp_base_t * v);
dp_base_t * dp_pl_rstat_get_mixer(receiver_stat_t *r);
void dp_pl_rstat_set_block_time_ms(receiver_stat_t *r,uint32_t  v);
uint32_t  dp_pl_rstat_get_block_time_ms(receiver_stat_t *r);
#endif
