
#include <inttypes.h>


/*
 * Filter Coefficients
 *
 * This file was automatically generated by the script:
 *
 * firdes/make_filters.pl 
 *
 * by scanning the following files for specially formatted comments
 * that cleverly (?) include the parameters of filters that will be 
 * referenced in the code in that file.  Included in the make process,
 * this allows changes in filter parameters in C files to immediately
 * be realized on the next compile, without having to copy/paste from
 * another tool.
 *
 * The follow files were scanned:
 *
 * src/dsp_chain.c
 *
 * In that scan, the follow variables were found:
 *
 * bp1020_sr6250_TEST
 * bp105_sr1250
 * bp30_sr1250
 * bp9960_sr31250
 * lp25k_sr250k
 * lp400_sr31250 
 *
 * Note that it is possible that some of those listed above had errors 
 * (which should have been reported during the make process, or the 
 * firdes subroutine just croaked, in which case those filters will 
 * not be present below and very likely the program that was expected
 * them to be there will not compile. :-(
 *
 *
 * Ran on Mon Sep  7 02:32:15 2015
 */


/*
---
bands:
  - 0
  - 9300
  - 9450
  - 10470
  - 10620
  - 15625
devs:
  - 0.001
  - 0.0575011277845372
  - 0.001
dtype: int16_t
errors: []
mags:
  - 0
  - 1
  - 0
name: bp9960_sr31250
num_bands: 3
num_taps: 275
remez_bands:
  - 0
  - 0.5952
  - 0.6048
  - 0.67008
  - 0.67968
  - 1
remez_mags:
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
remez_num_taps: 275
remez_type: 1
remez_weights:
  - 57.5011277845372
  - 1
  - 57.5011277845372
sample_rate: 31250
subtype: 1
type: fir
*/
extern uint32_t bp9960_sr31250_len;
extern int16_t bp9960_sr31250_coeffs[275];
/*
---
bands:
  - 0
  - 20000
  - 30000
  - 125000
devs:
  - 0.0575011277845372
  - 0.000316227766016838
dtype: int16_t
errors: []
mags:
  - 1
  - 0
name: lp25k_sr250k
num_bands: 2
remez_bands:
  - 0
  - 0.16
  - 0.24
  - 1
remez_mags:
  - 1
  - 1
  - 0
  - 0
remez_num_taps: 58
remez_type: 1
remez_weights:
  - 1
  - 181.834531827529
sample_rate: 250000
subtype: 1
type: fir
*/
extern uint32_t lp25k_sr250k_len;
extern int16_t lp25k_sr250k_coeffs[58];
/*
---
bands:
  - 0
  - 95
  - 100
  - 110
  - 115
  - 625
devs:
  - 0.001
  - 0.0575011277845372
  - 0.001
dtype: int16_t
errors: []
mags:
  - 0
  - 1
  - 0
name: bp105_sr1250
num_bands: 3
num_taps: 250
remez_bands:
  - 0
  - 0.152
  - 0.16
  - 0.176
  - 0.184
  - 1
remez_mags:
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
remez_num_taps: 250
remez_type: 1
remez_weights:
  - 57.5011277845372
  - 1
  - 57.5011277845372
sample_rate: 1250
subtype: 1
type: fir
*/
extern uint32_t bp105_sr1250_len;
extern int16_t bp105_sr1250_coeffs[250];
/*
---
bands:
  - 0
  - 20
  - 25
  - 35
  - 40
  - 625
devs:
  - 0.001
  - 0.0575011277845372
  - 0.001
dtype: int16_t
errors: []
mags:
  - 0
  - 1
  - 0
name: bp30_sr1250
num_bands: 3
num_taps: 250
remez_bands:
  - 0
  - 0.032
  - 0.04
  - 0.056
  - 0.064
  - 1
remez_mags:
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
remez_num_taps: 250
remez_type: 1
remez_weights:
  - 57.5011277845372
  - 1
  - 57.5011277845372
sample_rate: 1250
subtype: 1
type: fir
*/
extern uint32_t bp30_sr1250_len;
extern int16_t bp30_sr1250_coeffs[250];
/*
---
bands:
  - 0
  - 940
  - 990
  - 1050
  - 1100
  - 3125
devs:
  - 0.001
  - 0.0575011277845372
  - 0.001
dtype: int16_t
errors: []
mags:
  - 0
  - 1
  - 0
name: bp1020_sr6250_TEST
num_bands: 3
num_taps: 170
remez_bands:
  - 0
  - 0.3008
  - 0.3168
  - 0.336
  - 0.352
  - 1
remez_mags:
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
remez_num_taps: 170
remez_type: 1
remez_weights:
  - 57.5011277845372
  - 1
  - 57.5011277845372
sample_rate: 6250
subtype: 1
type: fir
*/
extern uint32_t bp1020_sr6250_TEST_len;
extern int16_t bp1020_sr6250_TEST_coeffs[170];
/*
---
bands:
  - 0
  - 400
  - 700
  - 15625
devs:
  - 0.0575011277845372
  - 0.000316227766016838
dtype: int16_t
errors: []
mags:
  - 1
  - 0
name: lp400_sr31250
num_bands: 2
remez_bands:
  - 0
  - 0.0256
  - 0.0448
  - 1
remez_mags:
  - 1
  - 1
  - 0
  - 0
remez_num_taps: 237
remez_type: 1
remez_weights:
  - 1
  - 181.834531827529
sample_rate: 31250
subtype: 1
type: fir
*/
extern uint32_t lp400_sr31250_len;
extern int16_t lp400_sr31250_coeffs[237];
